#!/bin/bash

echo "🚀 Carbon Recycling Platform - Deployment Setup"
echo "================================================"

# Check if git is initialized
if [ ! -d ".git" ]; then
    echo "📝 Initializing git repository..."
    git init
    git add .
    git commit -m "Initial commit: Complete Carbon Recycling Platform"
fi

# Get GitHub repository URL
echo ""
echo "📋 Next steps to deploy:"
echo ""
echo "1. Create a new GitHub repository called 'carbon-recycling-platform'"
echo "2. Run these commands to push your code:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/carbon-recycling-platform.git"
echo "   git push -u origin main"
echo ""
echo "3. Set up the following services:"
echo ""
echo "   🔐 Clerk (Authentication):"
echo "      → Create account at https://clerk.com"
echo "      → Create new application for carbonrecycling.co.uk"
echo "      → Get PUBLIC_CLERK_PUBLISHABLE_KEY and CLERK_SECRET_KEY"
echo ""
echo "   🗄️ PlanetScale (Database):"
echo "      → Create account at https://planetscale.com"
echo "      → Create database 'carbon-recycling-db'"
echo "      → Run schema from packages/db/schema.sql"
echo "      → Get DATABASE_URL connection string"
echo ""
echo "   ☁️ Cloudflare (Hosting):"
echo "      → Create API token with Pages & Workers permissions"
echo "      → Create Pages project connected to your GitHub repo"
echo "      → Set custom domain to carbonrecycling.co.uk"
echo "      → Create R2 bucket 'carbon-recycling-files'"
echo ""
echo "   📧 Resend (Email):"
echo "      → Create account at https://resend.com"
echo "      → Verify domain carbonrecycling.co.uk"
echo "      → Get API key"
echo ""
echo "   📄 Browserless.io (PDF Generation):"
echo "      → Create account at https://browserless.io"
echo "      → Get API key"
echo ""
echo "4. Configure environment variables:"
echo ""
echo "   GitHub Secrets:"
echo "   - CLOUDFLARE_API_TOKEN"
echo "   - CLOUDFLARE_ACCOUNT_ID" 
echo "   - PUBLIC_CLERK_PUBLISHABLE_KEY"
echo ""
echo "   Cloudflare Worker Variables:"
echo "   - CLERK_SECRET_KEY"
echo "   - DATABASE_URL"
echo "   - R2_BUCKET_NAME"
echo "   - R2_ACCESS_KEY_ID"
echo "   - R2_SECRET_ACCESS_KEY"
echo "   - R2_ENDPOINT"
echo "   - BROWSERLESS_API_KEY"
echo "   - RESEND_API_KEY"
echo ""
echo "5. Push to main branch to trigger deployment"
echo ""
echo "📚 See DEPLOYMENT.md for detailed instructions"
echo ""
echo "✅ Your platform will be live at https://carbonrecycling.co.uk"