name = "carbon-recycling-api"
main = "src/index.ts"
compatibility_date = "2024-09-30"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
# CLERK_PUBLISHABLE_KEY and CLERK_SECRET_KEY should be set as secrets
# Use: wrangler secret put CLERK_PUBLISHABLE_KEY
# Use: wrangler secret put CLERK_SECRET_KEY

[[kv_namespaces]]
binding = "CACHE"
id = "cache_namespace"
preview_id = "cache_preview"

# D1 Database Configuration
[[d1_databases]]
binding = "DB"
database_name = "carbon-recycling-platform"
database_id = "23916764-2973-4278-baf0-e6b419dec3ea"
